# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0002_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
