# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0003_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
