# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt', '0004_auto_20161215_0709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.TextField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
